apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: myapp-2-ns
  labels: 
    app: myapp-2
    name: postgres-pvc
spec:
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi













