apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: myapp-2-ns
  labels:
    app: myapp-2
    name: postgres-pv
spec: 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  hostPath:
    path: /data
    type: DirectoryOrCreate







